"""your message

Revision ID: 3a83453c12b4
Revises: 2e26c270015b
Create Date: 2024-07-01 12:15:53.405353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a83453c12b4'
down_revision = '2e26c270015b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
