"""your message

Revision ID: ef1f2b993563
Revises: 3a83453c12b4
Create Date: 2024-07-08 20:41:50.359910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1f2b993563'
down_revision = '3a83453c12b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
